let btn1 = document.getElementById('btn1');
let btn2 = document.getElementById('btn2');
let btn3 = document.getElementById('btn3');
let btn4 = document.getElementById('btn4');
let btn5 = document.getElementById('btn5');
let btnContent1 = document.getElementById('gs-btn-1');
let btnContent2 = document.getElementById('gs-btn-2');
let btnContent3 = document.getElementById('gs-btn-3');
let btnContent4 = document.getElementById('gs-btn-4');
let btnContent5 = document.getElementById('gs-btn-5');
let btnContent0 = document.getElementById('gs-btn-0');

btn1.addEventListener('click',pressed1);
btn2.addEventListener('click',pressed2);
btn3.addEventListener('click',pressed3);
btn4.addEventListener('click',pressed4);
btn5.addEventListener('click',pressed5);

function pressed1(e){
    btnContent0.style.display = "none";
    btn1.style.background = "#1ba94c";
    btn2.style.background = "none";
    btn3.style.background = "none";
    btn4.style.background = "none";
    btn5.style.background = "none";
    btnContent1.style.zIndex="1";
    btnContent2.style.zIndex="0";
    btnContent3.style.zIndex="0";
    btnContent4.style.zIndex="0";
    btnContent5.style.zIndex="0";
    btnContent1.style.height="550px";
    btnContent2.style.height="0";
    btnContent3.style.height="0";
    btnContent4.style.height="0";
    btnContent5.style.height="0";
    btnContent1.style.opacity="1";
    btnContent2.style.opacity="0";
    btnContent3.style.opacity="0";
    btnContent4.style.opacity="0";
    btnContent5.style.opacity="0";
    console.log(btnContent1);
    e.preventDefualt();
}
function pressed2(e){
    btnContent0.style.display = "none";
    btn2.style.background = "#1ba94c";
    btn1.style.background = "none";
    btn3.style.background = "none";
    btn4.style.background = "none";
    btn5.style.background = "none";
    btnContent1.style.zIndex="0";
    btnContent2.style.zIndex="1";
    btnContent3.style.zIndex="0";
    btnContent4.style.zIndex="0";
    btnContent5.style.zIndex="0";
    btnContent1.style.height="0";
    btnContent2.style.height="550px";
    btnContent3.style.height="0";
    btnContent4.style.height="0";
    btnContent5.style.height="0";
    btnContent1.style.opacity="0";
    btnContent2.style.opacity="1";
    btnContent3.style.opacity="0";
    btnContent4.style.opacity="0";
    btnContent5.style.opacity="0";
    e.preventDefualt();
}function pressed3(e){
    btnContent0.style.display = "none";
    btn3.style.background = "#1ba94c";
    btn2.style.background = "none";
    btn1.style.background = "none";
    btn4.style.background = "none";
    btn5.style.background = "none";
    btnContent1.style.zIndex="0";
    btnContent2.style.zIndex="0";
    btnContent3.style.zIndex="1";
    btnContent4.style.zIndex="0";
    btnContent5.style.zIndex="0";
    btnContent1.style.height="0";
    btnContent2.style.height="0";
    btnContent3.style.height="550px";
    btnContent4.style.height="0";
    btnContent5.style.height="0";
    btnContent1.style.opacity="0";
    btnContent2.style.opacity="0";
    btnContent3.style.opacity="1";
    btnContent4.style.opacity="0";
    btnContent5.style.opacity="0";
    e.preventDefualt();
}function pressed4(e){
    btnContent0.style.display = "none";
    btn4.style.background = "#1ba94c";
    btn2.style.background = "none";
    btn3.style.background = "none";
    btn1.style.background = "none";
    btn5.style.background = "none";
    btnContent1.style.zIndex="0";
    btnContent2.style.zIndex="0";
    btnContent3.style.zIndex="0";
    btnContent4.style.zIndex="1";
    btnContent5.style.zIndex="0";
    
    btnContent1.style.height="0";
    btnContent2.style.height="0";
    btnContent3.style.height="0";
    btnContent4.style.height="550px";
    btnContent5.style.height="0";
    btnContent1.style.opacity="0";
    btnContent2.style.opacity="0";
    btnContent3.style.opacity="0";
    btnContent4.style.opacity="1";
    btnContent5.style.opacity="0";
    e.preventDefualt();
}function pressed5(e){
    btnContent0.style.display = "none";
    btn5.style.background = "#1ba94c";
    btn2.style.background = "none";
    btn3.style.background = "none";
    btn4.style.background = "none";
    btn1.style.background = "none";
    btnContent1.style.zIndex="0";
    btnContent2.style.zIndex="0";
    btnContent3.style.zIndex="0";
    btnContent4.style.zIndex="0";
    btnContent5.style.zIndex="1";
    btnContent1.style.height="0";
    btnContent2.style.height="0";
    btnContent3.style.height="0";
    btnContent4.style.height="0";
    btnContent5.style.height="550px";
    btnContent1.style.opacity="0";
    btnContent2.style.opacity="0";
    btnContent3.style.opacity="0";
    btnContent4.style.opacity="0";
    btnContent5.style.opacity="1";
    e.preventDefualt();
}